### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#10]
## Descrição
Issue derecionado para a elaboração do Rich Picture

## Terefas
- [x] Os participante devem elaborar um Rich Picture;
- [x] Devem-se realizar debates sobre os resultados para posterior documentação;

## Critérios de aceitação
- [ ] Ter uma versão final de tabela do Rich Picture.

**Comment by DanielPortods** [comment]
### Algumas fontes para elaboração de um bom Rich Picture

https://www.betterevaluation.org/en/evaluation-options/richpictures

https://www.ics.uci.edu/~wscacchi/Software-Process/Readings/RichPicture.pdf

**Comment by DanielPortods** [comment]
![IMG_20210728_114828637](https://user-images.githubusercontent.com/48573556/127344546-6c79d90f-ef35-428d-b52b-1f53a57d6f20.jpg)

**Comment by omateusp** [comment]
Fiz uma versão inicial que ainda preciso melhorar, mas ficou assim:
![rich_picture](https://user-images.githubusercontent.com/37383185/127550764-bb3e91c8-bad0-4166-92f5-aad240b8eab6.jpg)

**Comment by Joao-Pedro-Moura** [comment]
![fg](https://user-images.githubusercontent.com/69908186/127558993-14bf9a54-a5b8-4d5a-9838-fb8ea4c97521.jpeg)

**Comment by NiloMendonca** [comment]
![Uploading RichPicture.jpg…]()

**Comment by NiloMendonca** [comment]
![RichPicture](https://user-images.githubusercontent.com/24305332/127561179-676e563a-3f9f-44c1-9d46-fa4988d6f57b.jpg)

**Comment by gabrielbpn** [comment]
![meu rich picture](https://user-images.githubusercontent.com/58351486/127563063-6e15aaef-68df-45b5-9033-1e9c937d0051.jpg)

**Comment by edsondearaujo** [comment]
Grupo, não tenho certeza se os devs e o banco de dados deveria está na ilustração do Rich Picture. Mas resolvi deixar, até mesmo para sanar tal dúvida.

![richpicture_Ed](https://user-images.githubusercontent.com/39536164/127566520-1ab58093-1717-426c-9b08-e1157c6a5d89.jpg)

**Comment by francisco1code** [comment]
![](https://raw.githubusercontent.com/francisco1code/docs/master/images/WhatsApp%20Image%202021-07-29%20at%2018.47.17.jpeg)

**Comment by enzoggqs** [comment]
![IMG_20210729_191817.jpg](https://user-images.githubusercontent.com/38733364/127572913-4f569335-66e5-4c62-a8ac-e5138a12b58e.jpg)

**Comment by eliseukadesh67** [comment]
![RichPicture](https://user-images.githubusercontent.com/48720096/127573518-3b916722-91f4-4c98-9154-cc57e420d05c.jpg)

**Comment by Bruno-Felix** [comment]
[rich_picture_Curumim.pdf](https://github.com/UnBArqDsw2021-1/2021.1_G6_Curumim/files/6904023/rich_picture_Curumim.pdf)

**Comment by Bruno-Felix** [comment]
![rich_picture_Curumim1-2](https://user-images.githubusercontent.com/38890440/127575585-fc368f27-4011-4319-9291-0803aa521ed5.jpg)

**Comment by Bruno-Felix** [comment]
![rich_picture_Curumim1-3](https://user-images.githubusercontent.com/38890440/127575663-40012611-e559-46c6-9eab-7580f8058132.jpg)
