### ISSUE TITLE
Revisão de documentação - Planejamento da Avaliação do Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by omateusp** [UnBArqDsw2021-1/2021.1_G6_Curumim#107]
### Descrição:

Issue direcionada para a revisão do artefato Planejamento da Avaliação do Protótipo de Alta Fidelidade

### Tarefas:

- [x] Rever/Padronizar nome na página e no menu.
- [x] Adicionar citações e/ou referência, para reforçar o embasamento. (Introdução, Metodologia)
- [x] Se existir, adicionar rastros para os debates em equipe, consensos, contrapontos, e outros (Todo as seções do documento)
- [x] Nos resultados adicionar elos com artefatos terceiros.
- [x] Adicionar mais referências.

### Critérios de aceitação:

- [x] Alterações efetuadas e publicadas;
- [x] Issue pontuada.

**Comment by edsondearaujo** [comment]
### Tarefas:
- [ ] Se existir, adicionar rastros para os debates em equipe, consensos, contrapontos, e outros (Todo as seções do documento)
- Não foram encontrados rastros de debates.

- [ ] Nos resultados adicionar elos com artefatos terceiros.
- Não encontramos artefatos de terceiros que poderiam ser adicionados ao documento de planejamento de teste.
