### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#11]
## Descrição
Issue derecionado para a elaboração das Personas que serão utilizadas nos story boards

## Terefas
- [x] Os participante devem sugerir personas e antipersonas;
- [x] Deve ser escolhidas ao menos 3 personas (Professor, Administrador e Pais/ Responsáveis) e 1 antipersona;
- Estudar perfil de profissionais de educação infantil.

## Critérios de aceitação
- [x] Ter um conjunto final de personas e antipersona.

**Comment by DanielPortods** [comment]
Como não teremos tempo para lançar questionário e traçar o perfil de usuário, aqui está um estudo que achei interessaante sobre o perfil do profissional de educação infantil. 

https://anais.unicentro.br/flicenciaturas/pdf/iiv2n1/102.pdf

**Comment by DanielPortods** [comment]
#### Gostaria de dar destaque a o seguinte trecho do artigo citado:

"Um ponto relevante a essa discussão sobre o perfil do professor deeducação infantil é a faixa etária dos mesmos. De acordo com a Coordenação Pedagógicade Educação Infantil, o quadro docente da Educação Infantil da Secretaria Municipal écomposto por professores entre seus 17 a 50 anos. Destes tem: 9 entre a faixa etária de17-20 anos, 7 entre 21-30, 4 professores entre 31-40 anos, e 3 entre 41-50 anos.Deixando claro que estes 23 profissionais são do sexo feminino, não tendo presente o sexo contrário.

Num plano abrangente, fica evidente, por mais que na sociedade atualainda os homens estejam à frente de vários segmentos e estejam em maior número emempregos, no campo da educação esse número cai, cedendo espaço para as mulheres,como constatado com os dados desse estudo. Nesse momento se faz relevante pontuar apesquisa realizada pela Unesco (2004, p.44), que veem a confirmar essa questão."
 
página 16.

**Comment by Bruno-Felix** [comment]
### Persona:
- Perfil;
- Desenho;
- Necessidade;
- Comportamento.

**Comment by Bruno-Felix** [comment]
### Persona 1 (Administrador):
#### Perfil:
- Suzana;
- 44 anos;
- Casada.
- 2 filhos;
- 20 anos de experiência em Pedagogia;
- Mestrado em educação infantojuvenil para portadores de necessidades especias.

#### Comportamento:
- Criteriosa;
- Comunicativa;
- Antenada ao mundo digital;
- Insperada;
- Amante dos animais.

#### Necessidade:
- Aproximar a comunidade do Centro Educacional;
- Estimular uma maior participação dos pais na educação das crianças;
- Ajudar a formar bons cidadãos;
- Inserir a tecnologia no sistema educacional.


### Professor:
#### Perfil:
- Poliana;
- 28 anos;
- Solteira;
- 2 cachorros;
- Vegana.

#### Comportamento:
- Agitada;
- Extrovertida;
- Animada;
- Conversa bastante;

#### Necessidade:
- Melhorar a comunicação com os pais/ responsáveis;
- Desenvolver atividades interativas e divertidas com as crianças;
- Adquirir experiencia na área de forma inovadora.
