### ISSUE TITLE
Modelagem logica do banco de dados

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#116]
### Descrição:

Realizar a modelagem lógica do banco de dados, e adicionar a documentação do projeto.

### Tarefas:
- [x] Revisar o MER e DER para certificar a coerência;
- [x] Desenvolver o diagrama de modelagem lógica.

### Critérios de aceitação:
- [x] Coerência na documentação;
- [x] Referencias e citações bibliograficas para reforçar o embasamento na documentação;

**Comment by DanielPortods** [comment]
@Bruno-Felix @edsondearaujo @eliseukadesh67 @enzoggqs @francisco1code @Joao-Pedro-Moura @NiloMendonca @omateusp Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim/116?planning-poker)

**Comment by edsondearaujo** [comment]
### Pareamento
Discussão sobre alguns artefatos, que facilitam o entendimento da modelagem do banco de dados #81 na hora de construir a diagramação do modelo lógico. 
![pareamento_Edson_Eliseu](https://user-images.githubusercontent.com/39536164/130829243-f112988b-3caa-489a-a4b3-bb7fffb9aa28.png)
