### ISSUE TITLE
Introspecção

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#13]
### Descrição:
Descrição da Issue.

### Tarefas:
- [x] Tarefa a ser feita;
- Tarefa a ser feita.

### Critérios de aceitação:
- [x] Critério a ser verificado;
- Critério a ser verificado.

**Comment by Bruno-Felix** [comment]
|ID|Requisito|
|--|--|
|**RNFI_01**|Sistema ser enxuto |
|**RNFI_02**|Sistema tenha segurança|
|**RNFI_03**|Sistema carregar uma página em menos de 2 segundos|
|**RNFI_04**|Sistema funcionar 24h por dia|
|**RNFI_05**|Sistema rodar em todos os dispositivos|
|**RNFI_06**|Sistema ter acessibilidade para usuários com dificuldades|
|**RNFI_07**|Sistema ter um design minimalista|
|**RNFI_08**|Sistema gerar relatório em menos de 15 segundos|
|**RNFI_09**|Centralizar suas atividades no seu celular|
|**RNFI_10**|Um bom sistema de autenticação|

**Comment by gabrielbpn** [comment]
Já está atualizado na documentação, mas só para fazer essa observação na issue: os requisitos não funcionais foram atualizados, após a utilização do artefato argumentação.

A tabela anterior foi após a utilização da introspecção e essa tabela abaixo após análise posterior, logo, talvez não tenha somente a ver com a introspecção, mas achei interessante relatar aqui a atualização.

|**RNFI_01**|Sistema carregar uma página em menos de 2 segundos|
|**RNFI_02**|Sistema funcionar 24h por dia|
|**RNFI_03**|Sistema deve ser responsivo|
|**RNFI_04**|Sistema ter acessibilidade para usuários com dificuldades|
|**RNFI_05**|Sistema apresentar as funcionalidades principais na tela inicial|
|**RNFI_06**|Sistema gerar relatório em menos de 15 segundos|
|**RNFI_07**|Centralizar suas atividades no seu celular|
|**RNFI_08**|Um bom sistema de autenticação em duas etapas|

Fecho agora a issue com a tabela atualizada.
