### ISSUE TITLE
GRASP

### ISSUE THREAD

**Issue by omateusp** [UnBArqDsw2021-1/2021.1_G6_Curumim#131]
### Descrição:
Issue direcionada para o desenvolvimento do documento sobre GRASP.

### Tarefas:
- [x] Estudo batedor (Bruno e Francisco)
- [x] Reunião com batedores (Todo mundo)

Tópicos a serem adicionados no documento:
- [x] Criador (mateus e kadesh)
- [x] Especialista (nilo e gabriel)
- [x] Controlador (Enzo - edson)
- [x] Invenção pura (Bruno - daniel)
- [x] Alta Coesão (joao - francisco)
- [x] Baixo Acoplamento (joao - francisco)
- [x] Indireção (Bruno - daniel)
- [x] Variações protegidas  (Enzo - edson)
- [x] Polimorfismo (nilo e gabriel)

### Critérios de aceitação:
- [x] Todo os tópicos criados e revisados na branch principal;
- [ ] Hiperlinks adicionados ao documento.

**Comment by omateusp** [comment]
criei a branch `doc/131_main` que vai servir como base para criar as outras e ponto de junção das mesmas

**Comment by DanielPortods** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim/131?planning-poker) with ZenHub @Bruno-Felix @edsondearaujo @eliseukadesh67 @enzoggqs @francisco1code @gabrielbpn @Joao-Pedro-Moura @NiloMendonca @omateusp

**Comment by NiloMendonca** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim/131?planning-poker) with ZenHub @Bruno-Felix @DanielPortods @edsondearaujo @eliseukadesh67 @enzoggqs @francisco1code @gabrielbpn @Joao-Pedro-Moura @omateusp

**Comment by DanielPortods** [comment]
Já haviamos pontuado essa issue. Também me confundi 😅 .
