### ISSUE TITLE
Argumentação

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#14]
### Descrição:
Issue direcionado para a realização da Argumentação.

### Tarefas:
- [x] Documentação da argumentação referente as discussões sobre o projeto.

### Critérios de aceitação:
- [x] Ter as preferências definidas.

**Comment by DanielPortods** [comment]
Encontrei essa fonte sobre argumentação e achei interessante a parte do Framework ACE. Acredito que podemos adaptar para o nosso projeto.

https://www.bdm.unb.br/bitstream/10483/9267/1/2014_AndreCruzAlvesCavalcante.pdf

**Comment by Bruno-Felix** [comment]
- Autenticação:

Nilo: "Discordo, Não é testável"
Todo mundo: "Concordo"

Resultado: Trocar para "Autenticação de 2 etapas"

**Comment by Bruno-Felix** [comment]
- Autenticação:

Nilo: "Discordo, Não é testável"
Todo mundo: "Concordo"

Resultado: Trocar para "Autenticação de 2 etapas"

**Comment by DanielPortods** [comment]
## Permanencia do requisito REQB_05

- Bruno: Acho que devemos tirar os gráficos dos requisitos visto que a aplicação não gerará dados que precisem ser representados em gráficos.
- Gabriel: Acho que podemos deixar o requisito com uma prioridade baixa.
- Edson: O gráfico faz parte do relatório geral que está bem centrado no escopo do projeto.
- Francisco: A presença dos alunos pode ser representada em gráficos
- Enzo: Como são crianças de até 5 anos, os responsáveis precisam leva-las até o centro educacional, o que os dá acerteza da presença na aula.
- João: Nem sempre será o responsável que levará a criança, o que faz que seja necessário os dados de presença.
- DECISÃO: Houve um consenso em retirar o requisito em questão com a condição de deixar os dados de presença.

## Identificação do tipo de usuário

- Bruno: Poderia ser criada uma página especifica somente para os administradores.
- João: Pode ser desenvolvido um ambiente comum para todos que diferencie os tipos de usuários a partir dos dados do mesmo.
- DECISÃO: Houve um consenso para desenvolver um ambiente comum para todos que diferencie os tipos de usuários a partir dos dados.

## Desenvolvimento Full-stack de cada feature

- Bruno: Acho que é melhor que os responsáveis pela feature deselvolva ela do banco ao front.
- Matheus: Não tenho experiência com esse tipo de trabalho e ficaria confuso com todas as frentes ao mesmo tempo.
- Bruno: Podem haver falhas na comunicação e prejudicar o desenvolvimento de um funcionalidade por completo.
- Mathes: Com o desenvolvimento da arquitetura o entendimento geral vai mitigar essas dificuldades.
- Bruno: Sinto que não tem muitas pessoas com aptidão ao front-end, o que pode sobrecarregar alguns integrantes.
- Francisco: A equipe tem muitos integrantes que podem ser alocados conforme a necessidade.
- DECISÃO: Houve um consenso em seguir o desenvolvimento modularizado com o cuidado para não sobrecarregar ninguém.

## Requisitos não funcionais

- Nilo: Alguns requisitos elicitados não podems ser caracterizados como requisitos não funcionais pois não podem ser testados.
- DECISÃO: Sem qualquer conflito, foram retirados os RNFI_01, RNFI_02 e RNFI_11 e, também, foram atualizados os RNFI_05 E RNFI_07.

**Comment by DanielPortods** [comment]
> Encontrei essa fonte sobre argumentação e achei interessante a parte do Framework ACE. Acredito que podemos adaptar para o nosso projeto.
> 
> https://www.bdm.unb.br/bitstream/10483/9267/1/2014_AndreCruzAlvesCavalcante.pdf

Para quem for documentar tudo. Nesse papper tem uma explicação muito boa sobre o modelo ACE.
Da página 38 a 40. Acredito que pode ser adaptado sem a utilização da Avaliação de aceitabilidade.
