### ISSUE TITLE
GOFs Comportamentais

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#146]
### Descrição:
Issue direcionada à criação do documento de GOFs comportamentais

### Tópicos:
- [x] Command (ENZO)
- [x] * Iterator ENZO - DANIEL)
- [x] Mediator (EDSON)
- [x] Observer 
- [x] * State (ENZO - DANIEL)
- [x] Strategy (EDSON)
- [x] Template Method - (EDSON)
- [x] Visitor (MATEUS)
- [x] Memento (MATEUS)
- [x] Chain Of Responsability (MATEUS)

### Critérios de aceitação:
- [x] Todo os tópicos criados e revisados na branch principal;
- [ ] Hiperlinks adicionados ao documento.

**Comment by edsondearaujo** [comment]
### Ref
[ IMPLEMENTAÇÃO DOS PADRÕESSTRATEGY E FACADE](https://revistas.unoeste.br/index.php/ce/article/view/1550/1612)

**Comment by edsondearaujo** [comment]
### Tópico:

- [ ] Template Method

Depois de algumas pesquisas e estudo dos materiais citados acima. Foi observado que o padrão Template Method é bem interessante, mas não consegui visualizar sua aplicação na arquitetura do nosso projeto.

**Comment by DanielPortods** [comment]
@omateusp e @edsondearaujo 
https://refactoring.guru/design-patterns
https://www.dofactory.com/javascript/design-patterns/

**Comment by edsondearaujo** [comment]
# Mediator

## Versionamento
| Versão | Data | Modificação | Autor |
|--|--|--|--|
|1.0|10/09/2021| Abertura do documento | Mateus O. Patrício |
|1.1|16/09/2021| Introdução ao Mediator e inclusão de bibliografia [2] | Edson Soares |
|1.2|16/09/2021| Inclusão do diagrama Mediator | Edson Soares |
|1.3|17/09/2021| Explicação do diagrama de classe | Edson Soares |
|1.4|19/09/2021| Construção da estutura de objetos | Edson Soares |
|1.5|19/09/2021| Implementação | Edson Soares |
