### ISSUE TITLE
First things First

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#15]
### Descrição:
Descrição da Issue.

### Tarefas:
- [x] Tarefa a ser feita;
- Tarefa a ser feita.

### Critérios de aceitação:
- [x] Critério a ser verificado;
- Critério a ser verificado.

**Comment by DanielPortods** [comment]
Tabela de priorização: https://docs.google.com/spreadsheets/d/1VO7EnKcoZ7DF_uIbGJHg4b3MkhtVpMwE/edit#gid=667435397
