### ISSUE TITLE
Revisão da documentação - Entrega 2

### ISSUE THREAD

**Issue by NiloMendonca** [UnBArqDsw2021-1/2021.1_G6_Curumim#161]
### Descrição:
Issue direcionada para a correção da parte textual dos artefatos produzidos para a entrega 2 da disciplina.

##### Diagrama de classe
- [x] Falta embasamento na literatura;
- [x] Sem elos com artefatos terceiros;
- [x] Referências não clicável;

##### Diagrama de pacotes
- [x]  Colocações iniciais muito breves e sem embasamento na literatura;
- [x] Sem uma seção dedicada à Metodologia;
- [x]  Sem elos com outros artefatos;
- [x] Referências não clicáveis;

##### Diagrama de componentes
- [x] Colocações iniciais muito breves e sem embasamento na literatura;
- [x] Falta texto, complementando o nível de modelagem;
- [x]  Sem elos com outros artefatos;

##### Diagrama de atividades
- [x] Colocações iniciais sem embasamento na literatura;
- [x]  Sem elos com outros artefatos;
- [x] Sem referências no texto;
- [x]  Apenas duas referências;

##### Diagrama de comunicação
- [x] Colocações iniciais sem embasamento na literatura;
- [x]  Sem elos com artefatos terceiros;
- [x] Sem referências no texto;

##### Diagrama de estados
- [x] Colocações iniciais sem embasamento na literatura;
- [x]  Sem elos com artefatos terceiros;
- [x] Sem referências no texto;

##### Diagrama de sequência
- [x] Colocações iniciais sem embasamento na literatura;
- [x]  Sem elos com artefatos terceiros;
- [x] Sem referências no texto;
- [ ] O template da especificação está diferente

##### Backlog do Produto
- [x] Épicos, Features e Histórias de Usuário sem apoio de referências da literatura

##### Casos de uso
- [x] Sem elos com artefatos terceiros;
- [x] Sem referência acordada no texto;

##### MER
- [x] Erros de escrita;
- [x]  Sem elos com artefatos terceiros;
- [x] Sem referência sendo acordada no texto;

##### DER
- [x]  Sem elos com artefatos terceiros;
- [x] Sem referência sendo acordada no texto;

### Critérios de aceitação:
- [ ] Todos os artefatos com alguma sugestão de alteração, alterados;
- [ ] Alterações publicadas;

**Comment by edsondearaujo** [comment]
### Revisar Diagramas (Edson)
- [ ] Classe;
- [ ] Atividades;
- [ ] Sequência;
- [ ] MER;
- [ ] DER;

**Comment by NiloMendonca** [comment]
## Revisar Diagramas (Nilo)
- [ ] Diagrama de pacotes;
- [ ] Diagrama de componentes;
- [ ] Diagrama de comunicação;
- [ ] Diagrama de estados;
- [ ] Casos de uso;

-----

- [ ] Backlog do Produto;

**Comment by edsondearaujo** [comment]
@NiloMendonca Precisamos ver a segunda referência do diagrama de classe. É um link para o aprender da disciplina, acho que não vale, já que é necessário realizar login para ter acesso, isso implica está matriculado na turma de desenho.
