### ISSUE TITLE
Padrões Emergentes

### ISSUE THREAD

**Issue by francisco1code** [UnBArqDsw2021-1/2021.1_G6_Curumim#167]
### Descrição:
Issue direcionada à criação do documento de padrões emergentes

### Tarefas:
- [x] Criar padrão Meddleware
- [x] Criar padrão MVC

### Critérios de aceitação:
- [x] Todo os tópicos criados e revisados
- [x] Review pelo PR

**Comment by Bruno-Felix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim/167?planning-poker) with ZenHub @enzoggqs @DanielPortods @Joao-Pedro-Moura @omateusp @NiloMendonca @eliseukadesh67 @gabrielbpn

**Comment by Bruno-Felix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim/167?planning-poker) with ZenHub @edsondearaujo @francisco1code
