### ISSUE TITLE
Prototipação

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#17]
### Descrição:
Issue direcionada para a realização da prototipação e planejamento do teste de usabilidade

### Tarefas:
- [ ] Desenvolver um prototipo de baixa fidelidade
- [ ] Planejar o teste 

### Critérios de aceitação:
- [ ] Prototipo pronto

**Comment by NiloMendonca** [comment]
![P_20210730_082842_1](https://user-images.githubusercontent.com/24305332/127648161-fc80d793-294b-4980-8c8e-4248f80fa425.jpg)

**Comment by omateusp** [comment]
Fiz as telas para o responsável
![protótipo](https://user-images.githubusercontent.com/37383185/127649002-749d89df-483d-4d99-88ce-12aa93b6265c.jpg)

**Comment by enzoggqs** [comment]
![IMG_20210730_084958_261.jpg](https://user-images.githubusercontent.com/38733364/127649017-fbe00983-32b5-40da-b462-45fd60f994eb.jpg)![IMG_20210730_085019_770.jpg](https://user-images.githubusercontent.com/38733364/127649024-c7ca5afd-fd31-4491-a520-498ac0717e0a.jpg)

**Comment by edsondearaujo** [comment]
HOME

![Home_BFidel](https://user-images.githubusercontent.com/39536164/127649531-858a8258-3033-45e7-b19d-fb5290184315.jpg)

**Comment by edsondearaujo** [comment]
Portal do ALUNO

![Aluno_BFidel](https://user-images.githubusercontent.com/39536164/127649656-289fb53a-ff9f-44fc-84e5-56a6f4b30893.jpg)

**Comment by eliseukadesh67** [comment]
Página Inicial do Admin:

![Admin-PagInicial](https://user-images.githubusercontent.com/48720096/127649840-d42fdc3f-309a-4cdf-8965-9d4c14f9fe9e.jpg)

**Comment by eliseukadesh67** [comment]
Página de Turmas do Admin : 

![Admin-PagTurmas](https://user-images.githubusercontent.com/48720096/127649925-207a8e69-09b8-4b24-a000-b96da0753bb1.jpg)

**Comment by DanielPortods** [comment]
## Essas são minhas ideias para a parte do responsável.

### Atividade
![WhatsApp Image 2021-07-30 at 08 53 30 (2)](https://user-images.githubusercontent.com/48573556/127649686-3c9f1fcd-3cd9-4f2f-a722-ab138f658956.jpeg)

### Tela com todas do aluno Atividades
![WhatsApp Image 2021-07-30 at 08 53 30 (1)](https://user-images.githubusercontent.com/48573556/127649725-56309ca7-7737-4e85-a701-1bf0dd7c3897.jpeg)

### Perfil da Criança
![WhatsApp Image 2021-07-30 at 08 53 30](https://user-images.githubusercontent.com/48573556/127649785-4d73d208-0724-4f2a-9c59-a2b0984813d4.jpeg)

### Menu lateral
![WhatsApp Image 2021-07-30 at 08 53 29 (2)](https://user-images.githubusercontent.com/48573556/127649791-568f6c06-28e7-4648-b475-409dca783b13.jpeg)

### Tela inicial do responsavel
![WhatsApp Image 2021-07-30 at 08 53 29 (1)](https://user-images.githubusercontent.com/48573556/127649798-4e47d274-f6aa-48ed-8e8b-d8f36f5cbfe3.jpeg)

###  Login
![WhatsApp Image 2021-07-30 at 08 53 29](https://user-images.githubusercontent.com/48573556/127649802-e80471d3-d983-42af-a5b9-a9312f695f55.jpeg),

### Agenda
![sdd](https://user-images.githubusercontent.com/48573556/127649811-b575abf0-2933-4922-948c-b4ed9cf691e1.jpeg)

### Observação da agenda do aluno
![asdfasdf](https://user-images.githubusercontent.com/48573556/127649821-f44142f8-e6a1-42f1-9b2a-26c1bd9549d4.jpeg)

**Comment by Joao-Pedro-Moura** [comment]
![WhatsApp Image 2021-07-30 at 09 04 47](https://user-images.githubusercontent.com/69908186/127650608-933b8036-3716-47fc-9b2e-a7e66c63006d.jpeg)

**Comment by Bruno-Felix** [comment]
![aux1](https://user-images.githubusercontent.com/38890440/127650936-cf086901-77f1-49fe-8dca-b49d25a769ba.jpeg)

**Comment by edsondearaujo** [comment]
Site para baixar ícones.

[Flaticon](https://www.flaticon.com/search?word=menu%20bar&type=icon&k=1627689016063)
