### ISSUE TITLE
Instalar Zenhub

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#18]
### Descrição:
Descrição da Issue.

### Tarefas:
- [x] Tarefa a ser feita;
- Tarefa a ser feita.

### Critérios de aceitação:
- [x] Critério a ser verificado;
- Critério a ser verificado.

**Comment by DanielPortods** [comment]
Já instalei a extensão do Zenhub no meu firefox e criei o workspace no nosso repo.
