### ISSUE TITLE
Quarta Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-1/2021.1_G6_Curumim#227]
Olá Pessoal!

O Grupo 06 irá avaliar o Grupo 04 nessa quarta avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 3: Arquitetura e Reutilização de Software do Moodle, e procurar por "Quarta Avaliação por Pares".

DEADLINE: 18 de Outubro de 2021, ao final do dia.

Atenciosamente.

**Comment by estevaoreis25** [comment]
marcos@mail.com
senha: 123456

Esse é um  login válido caso queiram acessar o site olhar as funcionalidades desenvolvidas para um corretor
