### ISSUE TITLE
Planejar Metodologia

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#4]
## Descrição
Issue direcionada para o planejamento e definição de uma metodologia para o desenvolvimento do projeto.

## Tarefas
- [x] Sugerir e debater adaptações de metodologias que se encaixem bem no contexto da equipe.

## Critérios de aceitação
- [x] Metodologia definida.

**Comment by DanielPortods** [comment]
## MInha sugestão
Sugiro que seja uma metodologia mista. Adaptada com a presença de praticas do SCRUM, do XP e do Kanban.

### Do SCRUM
- Sprint com duração de uma semana e início nas Segundas;
- Reuniões nos sábados para realização de review, retrospective e planning da sprint seguinte;
- Dailys de segunda a sexta no canal de texto do Discord.

### Do XP
- Adoção dos [valores do XP](http://www.extremeprogramming.org/values.html);
- Adoção de pair programming.

### Do Kanban
- Utilização da extensão ZenHub para auxiliar na organização e nas métricas.

**Comment by Bruno-Felix** [comment]
Aprovo as sugestões de metodologia
