### ISSUE TITLE
Planejar Padrão de contribuição e perfil de comunidade

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#5]
## Descrição:
Definir as políticas de contribuição do Projeto e também comtemplar todos os pontos do [perfil de comunidade](https://github.com/UnBArqDsw2021-1/2021.1_G6/community).

## Tarefas:
- [ ] Padrão de commit;
- [ ] Padrão de issues;
- [ ] Processo de contribuição;
- [ ] Padrão de branch;
- [ ] Modificar nome do repositório após termos nosso tema;
- [x] Inserir descrição;
- [x] Inserir README;
- [x] Inserir código de conduta;
- [ ] Inserir Contributing;
- [x] Inserir template de Issue;
- [ ] Inserir template de Pull request.

## Critérios de Aceitação:
- [x] Todos os integrantes concordarem com os padrões elaborados;

**Comment by Bruno-Felix** [comment]
Exemplo de commit: doc(#1): ducumento

**Comment by DanielPortods** [comment]
# Politica de branchs
## Fluxo de trabalho
### Main
- Branch que contém o código mais estável da aplicação e em nível de produção;
- Existe penas uma branch main;
- Não é permitidos commits feitos diretamente na main;
- Deve aceita apenas mesclagens de branches do tipo hotfix e releases;
- Nome: main.

### Develop
- Branch que contém a versão mais atualizada do código em nível de desenvolvimento;
- Existe penas uma branch develop;
- Existe apenas uma branch develop;
- Qualquer branch pode ser mesclada a develop;
- Nome: Develop

### Release
- Branch que representa um conjunto de funcionalidades, prontas para serem inseridas na main;
- Deve ser derivada da branch develop;
- Deve ser mesclada a branch master e, se tiver sido alterada, a develop após a release ser concluída;
- Nenhuma funcionalidade pode ser inserida ao ambiente de produção fora de uma release;
- Deve aceita apenas Inserções de branches do tipo bugfix;
- A cada nova release, a versão do produto deve modificada, acrescentando 1 ao número central;
- Deve ser marcada por uma 'tag' que representa o Número da Versão da release.
- Nome: release_v-xxx, onde xxx é o número da versão.

### Feature
- Branch direcionada ao desenvolvimento de uma nova funcionalidade do produto:
- Deve ser derivada da branch develop;
- Deve ser mesclado de volta a branch develop e excluida do projeto após a funcionalidade ser desenvolvida;
- Nome: feature/USXXX_issueID-Nome_da_Feature, onde XXX é o número da Use story;
- ***Nome: doc/issue_ID-Nome-do-artefato (para documentação).***

### Bugfix
- Branch direcionada à implementação de soluções de bugs e erros encontrados numa release:
- Deve ser derivada da branch release;
- Deve ser mesclada a branch release e excluida do projeto após a resolução do ponto abordado;
- Nome: bugfix/issueID-Nome_do_Bug.

### Hotfix
- Branch direcionada à implementação de soluções de bugs e erros emergentes encontrados em produção, na branch main;
- Deve ser derivada da branch main;
- Deve ser mesclada a branch main e a develop e excluida do projeto após a resolução do ponto abordado;
- A cada novo hotfix, a versão do produto deve ser modificada, acrescentando 1 ao último número;
- Nome: hotfix/issueID-Nome_do_Bug_v-xxx, onde xxx é o novo numero de versão.

**Comment by DanielPortods** [comment]
# Politica de commits

- Mensagens devem ser em português no gerúndio, e conter uma breve descrição do que foi feito;
- O commit deve apontar para a issue que está associado;
- Deve conter o tipo de commit: feat, fix ou doc;
- Exemplos:

> feat(#xx) Alterando rotina de cadastro.
> fix(#xx) Corrigindo e padronizando declaração de variáveis.
> doc(#xx) Documentando a priorização.

- Deve ser usado o **Co-authored-by** para identificar o pareamento.
