### ISSUE TITLE
Definir as tecnologias para o Back-end

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#52]
### Descrição:
Issue direcionada para a definição de quais técnologias serão utilizadas no Back-end

### Tarefas:
- [x] Definir técnologias para contrução da API;
- [x] Definir o Banco de dados;

### Critérios de aceitação:
- [x] Tarefas realizadas;

**Comment by DanielPortods** [comment]
Então, pessoal. Eu tenho alguma experiência com Node.js + express + MongoDB usando arquitetura MVC.
Tenho vontado de aprender Django.

**Comment by francisco1code** [comment]
### Construção de API: 
Noje.js + Docker + Docker-compose + Arquitetura MVC
### Bancos de Dados:
 Postgres + ORM (Sequelize)
### Testes:
 Jest

### Pq essas stacks?:

O motivo dessas escolhas são por motivos de familiaridade com as stacks.

**Comment by DanielPortods** [comment]
Eu usaria essa sem problemas

**Comment by eliseukadesh67** [comment]
> ### Construção de API:
> Noje.js + Docker + Docker-compose + Arquitetura MVC
> 
> ### Bancos de Dados:
> Postgres + ORM (Sequelize)
> 
> ### Testes:
> Jest
> 
> ### Pq essas stacks?:
> O motivo dessas escolhas são por motivos de familiaridade com as stacks.

Tbm usaria, essa ta otima pra mim, compartilho da mesma familiaridade

**Comment by omateusp** [comment]
Das que a galera comentou aí eu já usei django rest (muito fácil fazer uma api com ela inclusive), se quiserem node.js preciso aprender, mas n seria um problema tbm

**Comment by DanielPortods** [comment]
Sobre o Django, é de boa pra encaixar nos paradigmas da disciplina?

**Comment by edsondearaujo** [comment]
Também tenho mais familiaridade com a stack que o Francisco comentou. Mas tenho vontade de trabalhar com [django rest](https://www.django-rest-framework.org/), sempre ouço falar que é fácil trabalhar com django.

**Comment by francisco1code** [comment]
Sou bem flexivel em relação as stacks, oq definirem estou dentro.

![](https://media.giphy.com/media/zhS4PEVVuFnbG718kV/giphy.gif)

**Comment by DanielPortods** [comment]
O que os senhores acham, então da stack Django rest + postgres + docker + docker compose ?
@omateusp sabe dizer se o Django combina bem com arquitetura mvc ?

**Comment by omateusp** [comment]
Olha, eu não sou nenhum expert em django rest como eu disse só usei 1x pro trabalho de PI e foi bem tranquilo, então se quiserem ir com a que vcs manjam mais pra ter alguém q manje bem da tecnologia também é válido e estou bem flexível quanto à tecnologia. Quanto à arquitetura, o django rest é MVC sim. Aconselho a darem uma olhada na doc antes de escolher https://www.django-rest-framework.org/

**Comment by DanielPortods** [comment]
Visto o que o @omateusp mencionou a pouco e que nós temos maior familiaridade com a stack citada pelo @francisco1code, todos concordam em utiliza-la? 

> ### Construção de API:
> 
> Noje.js + Docker + Docker-compose + Arquitetura MVC
> ### Bancos de Dados:
> 
> Postgres + ORM (Sequelize)
> ### Testes:
> 
> Jest
> ### Pq essas stacks?:
> 
> O motivo dessas escolhas são por motivos de familiaridade com as stacks.

**Comment by omateusp** [comment]
Estou de acordo

**Comment by edsondearaujo** [comment]
Concordo

**Comment by DanielPortods** [comment]
Tendo definidas as técnologias, essa issue pode ser encerrada.

**Comment by DanielPortods** [comment]
Eae pessoal, teve um impasse quanto ao banco de dados na reunião. Como podemos fazer para definir de forma rápida e eficiente esse tópico?

**Comment by DanielPortods** [comment]
Foi decidio manter com a utilização do postgres.
