### ISSUE TITLE
Revisar e corrigir os hiperlinks para os léxicos

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#53]
### Descrição:
Devem ser revisados os hiperlinks para os léxicos de cada documento.
 - Cada membro devera revisar os hiperlinks dos documentos que criaram até então;
 - Caso não tenham erros, devem comentar nessa issue que está tudo certo;
 - Se houverem erros ou o documento não tenho os links, devem criar branchs para realizar as correções.
 - O nome da branch será da forma : doc/53-links-***nome-do-integrante***;
 
### Tarefas:
- [x] Revisar os links dos documentos;
- [x] Corrigir ou criar os links.

### Critérios de aceitação:
- [ ] Todos os documentos até então terem links dos lexicos;
- [x] Todos os integrantes derem suas pontuações no Planning Poker.

**Comment by gabrielbpn** [comment]
Corrigi os hiperlinks do readme, doc do design sprint e da introspecção.

**Comment by DanielPortods** [comment]
Só pra lembrar que foi definido que os prs relacionados a esse issue só precisam de um revisor.

**Comment by gabrielbpn** [comment]
Opa. Tirei um revisor lá então. Valeu pelo aviso.
