### ISSUE TITLE
Definir as tecnologias para o Front-end

### ISSUE THREAD

**Issue by enzoggqs** [UnBArqDsw2021-1/2021.1_G6_Curumim#57]
### Descrição:
Issue direcionada para a definição de quais tecnologias serão utilizadas no Front-end

### Tarefas:
- [ ] Definir a Linguagem a ser utilizada.
- [ ] Definir a biblioteca a ser utilizada.

### Critérios de aceitação:
- [ ] Tecnologias estarem escolhidas;
- [ ] Todos os integrantes derem suas pontuações no Planning Poker.

**Comment by enzoggqs** [comment]
Eu já mexi com Vue.js e React.js, mas eu pessoalmente gostaria mais de trabalhar com React, pois acredito que o leque de oportunidades é maior, além de que é mais fácil encontrar documentação e respostas de dúvidas em React do que em Vue.

**Comment by NiloMendonca** [comment]
Já mexi com o Vue.js e com AngularJS, gosto bastante do Vue.js mas não me importo em trabalhar com qualquer outro framework/linguagem.

**Comment by Bruno-Felix** [comment]
Só tenho familiaridade com Vue.js e uma base bem rasa de Rreact.js. Estou aberto a trabalhar com qualquer uma.

O que o Enzo falou pode ser uma verdade...

**Comment by gabrielbpn** [comment]
Já trabalhei minimamente com React, mas nada demais. Considero a fala do Enzo de ser mais fácil achar as coisas em React um ponto importante.

**Comment by Joao-Pedro-Moura** [comment]
O ponto levantado pelo Enzo me convenceu bastante, já que não tenho muita experiência com esses Frameworks.

**Comment by Bruno-Felix** [comment]
Então ficamos entre React e Vue.

@enzoggqs consegue puxar o incio de React? Pq vou ter q aprender muito...

**Comment by enzoggqs** [comment]
O início acho q eu dou conta

**Comment by Bruno-Felix** [comment]
Então fechou React pessoal?w

**Comment by NiloMendonca** [comment]
Por mim ok

**Comment by Joao-Pedro-Moura** [comment]
Fechado!

**Comment by gabrielbpn** [comment]
Fechado.

**Comment by Bruno-Felix** [comment]
Considerar nossa tecnologia definida e a issue concluída.
