### ISSUE TITLE
Definir Nome do Projeto

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6_Curumim#6]
## Descrição
Issue direcionado para a definição do nome do projeto.

## Tarefas
- [x] Debater sugestões de nomes

## Critérios de aceitação
- [x] Nome definido

---
### Nome Definido: Curumim

**Comment by DanielPortods** [comment]
Na realização do Unpack, notei que muitos já estão utilizando o nome **AtividApp**. Podemos então seguir com esse? alguém tem alguma outra sugestão ou questão contra essa nome?

**Comment by Bruno-Felix** [comment]
Realmente isso ocorreu.

Não tenho nenhum problema. Mas acredito que o foco da aplicação não seria a atividade em sim. Mas a relação entre Centro - Pais

**Comment by Bruno-Felix** [comment]
Nome do Aplicativo: Curumim
