### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#8]
## Descrição
Issue derecionado para a aplicação da técnica de mapa mental.

## Terefas
- [x] Cada participante deve produzir um mapa mental e publicar nessa issue;
- [x] Devem-se realizar debates sobre os resultados para posterior documentação.

## Critérios de aceitação
- [x] Ter uma versão final de mapa mental pronto.

**Comment by eliseukadesh67** [comment]
* Com base nos resultados do nosso **Brainstorm**, este foi o mapa mental resultante da minha interpretação do escopo: 


![MapaMental](https://user-images.githubusercontent.com/48720096/127235928-ec9ea33b-0a36-42c4-a70c-8d146b398ff0.jpg)

**Comment by gabrielbpn** [comment]
O seu ficou bonito, Eliseu. Só perde pro meu 😎.
Brinks. 

Fiz o meu com um pouco mais de animação (com os emojis ali) que nem o 1° mapa mental apresentado pela professora na aula de mapas mentais. Não sei se isso deixa ela menos técnico ou profissional, mas na verdade acho que não.

![Mind Map (2)](https://user-images.githubusercontent.com/58351486/127236898-e0eccf68-edcc-4a24-904a-2bc07375f975.jpg)

**Comment by omateusp** [comment]
O meu ficou um pouco diferente kk
![mapa_mental](https://user-images.githubusercontent.com/37383185/127238493-d95a21b8-98cb-4ab3-8800-cd7505fee422.jpg)

**Comment by NiloMendonca** [comment]
O meu ficou bem parecido, fiz as subdivisões a partir dos principais utilizadores do sistema.
![Mind Map](https://user-images.githubusercontent.com/24305332/127238238-33090fee-b0a6-4f63-9458-98efc529554e.jpg)

**Comment by Bruno-Felix** [comment]
![Mind Map](https://user-images.githubusercontent.com/38890440/127241774-0327d34a-1989-4542-b4e7-9e6d7e954e61.jpg)

**Comment by DanielPortods** [comment]
![mind-map-daniel](https://user-images.githubusercontent.com/48573556/127242806-5f614972-f2d3-40c6-b3a2-3914403a37ea.png)

**Comment by francisco1code** [comment]
O meu fico bem simples, estava sem ideias kkkkkkk

![](https://raw.githubusercontent.com/francisco1code/docs/master/images/anatomy%20of%20film%20(1).gif)

**Comment by enzoggqs** [comment]
Essa foi a visão que eu tive da aplicação, acabou ficando bem simples mas acredito que abrange o escopo todo

![image](https://user-images.githubusercontent.com/38733364/127246920-26f20943-7e99-478f-a845-caffca8ab246.png)

**Comment by DanielPortods** [comment]
Eu achei que os mapas mentais feitos no miro ficaram mais bonitos.

**Comment by edsondearaujo** [comment]
Segue minha interpretação em mapa mental de acordo com o nosso Brainstorm.

![mindmap_ed](https://user-images.githubusercontent.com/39536164/127260529-8be73383-efe8-4d5d-ab05-12738c361228.PNG)

**Comment by Joao-Pedro-Moura** [comment]
Esse foi o mapa mental que fiz de acordo com o que temos até o momento.
![atividapp](https://user-images.githubusercontent.com/69908186/127275083-1bf11bc2-7365-4b7d-b74c-2aa8310c5637.png)

**Comment by Bruno-Felix** [comment]
## Grupo:

![Mind Map (1)](https://user-images.githubusercontent.com/38890440/127413188-748cf292-6392-4b05-bc3f-9319f4e4de3a.jpg)
