### ISSUE TITLE
Construir Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by francisco1code** [UnBArqDsw2021-1/2021.1_G6_Curumim#83]
### Descrição:
Essa issue tem como objetivo descrever as tarefas que serão abordadas durante a construção do ambiente de desenvolvimento.

### Tarefas:

* **Front-end**
    - [x] Criar Repositório
    - [x] Ambientação do React
    - [x] Conteinizar Ambiente
    - [x] Pipeline CI/CD

*  **Back-end**
    - [x] Criar Repositório
    - [x] Ambientação do node
    - [x] Ambientação DB postgres
    - [x] Conteinizar Ambiente
    - [x] Pipeline CI/CD

### Critérios de aceitação:
- [x]  Todos os integrantes derem suas pontuações no Planning Poker.
- [x]  Todos os membos conseguirem rodar o ambiente na sua maquina local.

**Comment by francisco1code** [comment]
@omateusp temos que definir uma plataforma para podemos fazer o deploy da aplicação para o CD, as plataformas que tenho experiencia é a AWS (Baixo)  e Heroku (Medio).

**Comment by francisco1code** [comment]
Álem disso depois que definir a plataforma, tbm temos que ver qual arquitetura que iremos usar, exemplo micro-serviços .... e se vamos usar imagens docker para o a pipeline, ou a propria aplicação.

**Comment by omateusp** [comment]
Quanto às plataformas de deploy, tenho mais experiência com GCP e AWS. No caso vamos ter só 1 API então acredito que usar uma imagem docker seria interessante.

**Comment by francisco1code** [comment]
Repositório do [Back-End](https://github.com/UnBArqDsw2021-1/2021.1_G6_Curumim-Back-end) foi criado!

**Comment by omateusp** [comment]
A pipeline de CI/CD foi definida mas ainda será implementada.
