### ISSUE TITLE
5W2H

### ISSUE THREAD

**Issue by DanielPortods** [UnBArqDsw2021-1/2021.1_G6_Curumim#9]
## Descrição
Issue derecionado para a aplicação da técnica 5W2H

## Terefas
- [x] Cada participante deve responder as perguntas da técnica;
- [x] Devem-se realizar debates sobre os resultados para posterior documentação;

## Critérios de aceitação
- [x] Ter uma versão final de tabela 5W2H.

**Comment by omateusp** [comment]
5W2H Produzido a partir do que discutimos no brainstom

- O que?
AtividApp, um aplicativo que facilita e agiliza a comunicação entre pais e mantenedores de um centro educacional, provendo informações sobre atividades e presença de seus filhos.

- Quem?
Grupo 6 da disciplina de Desenho e Arquitetura de Software

- Onde?
A ideia inicial é para um centro educacional específico, podendo ser replicado em outros centros.

- Por quê?
Para facilitar o acompanhamento dos filhos de até 5 anos pelos pais.

- Quando?
No 1º semestre letivo de 2021 da Universidade de Brasília(UnB)

- Como?
Os gerentes do centro educacional irão cadastrar os alunos, adicionar informações sobre os mesmos também podendo mandar notícias sobre o centro educacional ou até mesmo eventos e atividades. Já os pais poderão acessar relatórios sobre o mesmo ou entrar em contato com o centro.

- Quanto?
Valor a ser descrito no TAP

**Comment by gabrielbpn** [comment]
Minha visão e respostas sobre o artefato 5W2H:

- O que?
Um projeto chamado AtividApp em prol da melhoria de centros educacionais.

- Quem?
Será feito pelo grupo 6 da matéria Arquitetura e Desenho de Software do 1° semestre letivo do ano de 2021.

- Onde?
Será feito pela internet.

- Por quê?
O objetivo é melhorar a comunicação entre pais e professores em centros educacionais, onde as informações fiquem centralizadas em um só lugar.

- Quando?
O processo já começou a ser feito: desde o dia 20 de julho de 2021.

- Como?
Será feito e colocado num aplicativo ou aplicação web, após a codificação e o gerenciamento desse projeto.

- Quanto?
A princípio, não sei exatamente o valor que isso custará, já que a hora de cada integrante do grupo difere e não temos experiência suficiente para designar as coisas valiosas que faltam.

**Comment by NiloMendonca** [comment]
O que eu consegui fazer ...

| O que?(What) | Quem?(Who) | Onde?(Where) | Porque?(Why) | Quando?(When) | Como?(How) | Quanto?(How Much) |
| -- | -- | -- | -- | -- | -- | -- |
| Uma aplicação para um Centro Educacional que atende crianças de até 5 anos que ajudará no gerenciamento de atividades e na comunicação com a comunidade participante | Equipe 6 da disciplina de desenho e arquitetura de software | Poderá ser utilizado pelos administradores e professores do Centro Educacional, assim como os pais dos estudantes através de uma aplicação móvel para dispositivos Android | Para facilitar a comunicação e o acesso a informações entre pais e o Centro Educacional | Ao final do 2º semestre de 2021 | A aplicação contará basicamente com três tipos de usuários: Os administradores do Centro Educacional que terão opções de adicionar/editar/remover cadastros de professores, turmas e eventos, os professores que poderão criar/editar/remover atividades e os pais que poderão visualizar a informações disponibilizadas pelos dois outros usuários | O valor para a produção do aplicativo |

**Comment by Bruno-Felix** [comment]
O que?
 - O aplicativo é uma ferramenta de comunicação entre o Centro Acadêmico e os pais das crianças ali matriculadas. Através da plataforma os pais poderão acompanhar as atividades realizadas em sala de aula, os eventos festivos e ter uma linha direta de dialogo tanto com o professor, tanto com a administração da instituição.

Quem?
 - Alunos da Universidade de Brasília (UnB)

Quando?
 - No 1º semestre letivo de 2021.

Onde?
 - Virtualmente, na disciplina Arquitetura e Desenho de Software

Por que?
 - Para auxiliar e facilitar a comunicação entre os pais e o centro acadêmico, além do monitoramento das atividades realizadas por seus filhos.

Como?
 - Será feita um aplicativo para uso dos pais.

Quanto?
 - A Confirmar

**Comment by francisco1code** [comment]
![5w2h](https://raw.githubusercontent.com/francisco1code/docs/master/images/5w2h.png)

**Comment by DanielPortods** [comment]
| What? | Who? | Where? | Why? | When? | How? | How much? |
| -- | -- | -- | -- | -- | -- | -- |
| AtividApp, plataforma para ajudar no gerenciamento das atividades de um centro de ensino. | Integrantes do grupo 6 da disciplina de Arquitetura e desenho de software da UnB. | O desenvolvimento será realizado de forma totalmente remota. Incluindo, também, todas as reuniões e discussões. | Para ajudar no acompanhamento das participações das crianças nas atividades do centro de ensino por parte dos responsáveis. | Será feito durante o primeiro semestre letivo de 2021 que vai de 19/06 até  06/11. | Será adaptada uma metodologia que aplique conceitos de metodologias ágeis como scrum, xp e kanbam. | Terá o custo baseado no tempo e no esforço dos integrantes da equipe 6. O custo será detalhado nos artefatos de estimativas. |

**Comment by DanielPortods** [comment]
> ![5w2h](https://raw.githubusercontent.com/francisco1code/docs/master/images/5w2h.png)

1p1c2o3q  😋 😋

**Comment by francisco1code** [comment]
![](https://media.giphy.com/media/bzOwkffoJcEXcP2OxW/giphy.gif)

=p

**Comment by enzoggqs** [comment]
*What?*
Um aplicativo para um centro educacional, voltado para crianças, para auxiliar os pais no controle das atividades de seus filhos estão realizando no local.

*Why?*
O intuito é ajudar no monitoramento das atividades que os filhos estão praticando.

*Who?*
Um grupo de estudantes de Engenharia de Software na UnB.

*Where?*
No centro educacional, pelos professores e administradores e pelos pais dos alunos acessando a aplicação mobile.

*When?*
Durante o primeiro 1º período de 2021 na UnB.

*How?*
Os professores irão montar suas turmas na aplicação e lá darão as informações necessárias sobre os alunos, os pais dos alunos terão acesso as turmas de seus respectivos filhos e poderão também se comunicar com o professor de forma privada. E ao redor de tudo terá um administrador para mediar tudo que acontece.

*Quanto?*
A princípio não há um valor proposto.

**Comment by eliseukadesh67** [comment]
Meu 5W2H :

| O que                                                                                                                         | Como                                                                                                                                                                                                             | Onde                                                             | Quando              | Por que                                                                                              | Quem                                                       | Quanto custa |
|-------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------|---------------------|------------------------------------------------------------------------------------------------------|------------------------------------------------------------|--------------|
| Uma aplicação que possibilita a comunicação entre uma instituição  de ensino para crianças de até 5 anos e seus responsáveis. | Através de uma plataforma com informativos sobre atividades e eventos,  foruns e chats entre a instituição, professores e responsáveis, e também notificações  aos responsáveis sobre a situação do(s) filho(s). | Em uma aplicação feita para uma instituição de ensino específica. | 2º Semestre de 2021. | Facilitar a comunicação entre instituição e os responsáveis das crianças,  e oferecer transparência. | Administradores da insituição, professores e responsáveis. | A definir.   |

**Comment by DanielPortods** [comment]
Notei que houveram algumas divergências. Querem tirar dúvidas ?

**Comment by edsondearaujo** [comment]
![5w2h_ed](https://user-images.githubusercontent.com/39536164/127257068-09c86b61-de32-48f1-aeec-67262b99a1ec.PNG)

**Comment by Joao-Pedro-Moura** [comment]
![Sem título](https://user-images.githubusercontent.com/69908186/127392126-a34eafe1-7ec2-4fc5-9e0a-f655a7871adb.png)

**Comment by Bruno-Felix** [comment]
## Grupo:

- O que?
É uma aplicação de acompanhamento, por parte dos pais ou responsáveis, das atividades feitas por suas crianças no Centro Educacional.

- Quem?
Grupo 6 da disciplina de Arquitetura e Desenho de Software, da Universidade de Brasília(UnB).

- Quando?
Durante o primeiro semestre letivo de 2021 que vai de 19/06 até 06/11.

- Onde?
Totalmente Remoto.

- Por que?
Para acompanhar as atividades dos filhos, bem como facilitar a comunicação com o Centro Educacional.

- Como?
Será adaptada uma metodologia que aplique conceitos de metodologias ágeis.

- Quanto?
A definir no TAP.
