### ISSUE TITLE
Revisão da documentação - Entrega 1

### ISSUE THREAD

**Issue by omateusp** [UnBArqDsw2021-1/2021.1_G6_Curumim#98]
### Descrição:

Como não foi possível realizar todas as alterações sugeridas no feedback da primeira entrega decidimos que cada membro irá criar issues, referente aos documentos que criou com o que deve ser alterado, a fim de gerar rastreabilidade sobre as alterações necessárias.

### Tarefas:
Todos os membros devem ler o feedback da primeira entrega:
- [x] Bruno Alves Félix
- [x] Daniel Porto de Souza
- [x] Edson de Araújo Soares
- [x] Eliseu Kadesh Rosa Assunção Júnior
- [x] Enzo Gabriel Guedes Queiroz Saraiva
- [x] Francisco Emanoel Ferreira da Penha
- [x] Gabriel Bonifácio Perez Nunes
- [ ] João Pedro Elias de Moura
- [x] Mateus Oliveira Patrício
- [x] Nilo Mendonça de Brito Júnior

Todos os Membros devem criar issues sobre os documentos que participaram (conferir as issues criadas para não acontecerem issues duplicadas):
- [x] Bruno Alves Félix
- [ ] Daniel Porto de Souza
- [x] Edson de Araújo Soares
- [x] Eliseu Kadesh Rosa Assunção Júnior
- [x] Enzo Gabriel Guedes Queiroz Saraiva
- [x] Francisco Emanoel Ferreira da Penha
- [ ] Gabriel Bonifácio Perez Nunes
- [ ] João Pedro Elias de Moura
- [x] Mateus Oliveira Patrício
- [x] Nilo Mendonça de Brito Júnior

### Critérios de aceitação:
- [ ] Todos terem realizado as tarefas propostas;
- [ ] Issues criadas e comentadas.

**Comment by eliseukadesh67** [comment]
Minha issue de revisão do documento de custos esta contida na issue #104 do TAP
